/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autoventasbd2kevinramirez;

import java.sql.CallableStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class ActualizarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarVehiculo
     */
    public ActualizarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdMarca = new javax.swing.JTextField();
        btnConsultarVin = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnActualizarVehiculo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        txtNombreMarca = new javax.swing.JTextField();
        txtNombreEstado = new javax.swing.JTextField();
        btnConsultarMarca = new javax.swing.JButton();
        btnConsultarEstado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Actualizar Vehiculo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("VIN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Id marca");

        btnConsultarVin.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarVin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarVin.setText("Consultar");
        btnConsultarVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVinActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Modelo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Año");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Placa");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Id estado");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Color");

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSalir.setText("Regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnActualizarVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarVehiculo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnActualizarVehiculo.setText("Actualizar");
        btnActualizarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVehiculoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Precio venta");

        txtPrecioVenta.setEditable(false);

        txtNombreMarca.setEditable(false);

        txtNombreEstado.setEditable(false);

        btnConsultarMarca.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarMarca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarMarca.setText("Consultar");
        btnConsultarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMarcaActionPerformed(evt);
            }
        });

        btnConsultarEstado.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarEstado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarEstado.setText("Consultar");
        btnConsultarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarVehiculo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVin, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtModelo)
                            .addComponent(txtPlaca)
                            .addComponent(txtColor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarVin)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(txtIdEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIdMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreMarca)
                            .addComponent(txtNombreEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarMarca)
                            .addComponent(btnConsultarEstado))))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarVin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtIdMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarMarca))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtIdEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarEstado))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarVehiculo)
                            .addComponent(btnSalir))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        new Vehiculo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultarVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVinActionPerformed

 try {
        Connection conn = SesionUsuario.conexion;

        // Llamada al procedimiento que consulta datos del vehículo
        CallableStatement cs = conn.prepareCall("{ call PROYECTOBD.consultar_vehiculo_por_vin(?, ?, ?, ?, ?, ?, ?, ?) }");

        String vin = txtVin.getText().trim();
        cs.setString(1, vin);

        cs.registerOutParameter(2, java.sql.Types.INTEGER); // id_marca
        cs.registerOutParameter(3, java.sql.Types.VARCHAR); // placa
        cs.registerOutParameter(4, java.sql.Types.INTEGER); // id_estado
        cs.registerOutParameter(5, java.sql.Types.VARCHAR); // modelo
        cs.registerOutParameter(6, java.sql.Types.INTEGER); // anio
        cs.registerOutParameter(7, java.sql.Types.VARCHAR); // color
        cs.registerOutParameter(8, java.sql.Types.NUMERIC); // precio_venta

        cs.execute();
        //Se verifica si idMarca tiene algun valor para definir que si existe el vin
        int idMarca = cs.getInt(2); // p_id_marca
        if (cs.wasNull()) {
        JOptionPane.showMessageDialog(this, "No se encontró un vehículo con el VIN ingresado.");
        txtVin.setText("");
        txtVin.requestFocus();
        cs.close();
        return;
        }

        int idEstado = cs.getInt(4);

        txtIdMarca.setText(String.valueOf(idMarca));
        txtPlaca.setText(cs.getString(3));
        txtIdEstado.setText(String.valueOf(idEstado));
        txtModelo.setText(cs.getString(5));
        txtAño.setText(String.valueOf(cs.getInt(6)));
        txtColor.setText(cs.getString(7));
        txtPrecioVenta.setText(String.valueOf(cs.getBigDecimal(8)));

        cs.close();

        // ✅ Obtener nombre de la marca
        CallableStatement csNombreMarca = conn.prepareCall("{ ? = call proyectobd.obtener_nombre_marca(?) }");
        csNombreMarca.registerOutParameter(1, java.sql.Types.VARCHAR);
        csNombreMarca.setInt(2, idMarca);
        csNombreMarca.execute();
        txtNombreMarca.setText(csNombreMarca.getString(1));
        csNombreMarca.close();

        // ✅ Obtener nombre del estado
        CallableStatement csNombreEstado = conn.prepareCall("{ ? = call proyectobd.obtener_nombre_estado(?) }");
        csNombreEstado.registerOutParameter(1, java.sql.Types.VARCHAR);
        csNombreEstado.setInt(2, idEstado);
        csNombreEstado.execute();
        txtNombreEstado.setText(csNombreEstado.getString(1));
        csNombreEstado.close();


    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al consultar vehículo: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_btnConsultarVinActionPerformed

    private void btnActualizarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVehiculoActionPerformed
        // TODO add your handling code here:
    try {
       Connection conn = SesionUsuario.conexion;

        CallableStatement cs = conn.prepareCall("{ call proyectobd.actualizar_vehiculo(?, ?, ?, ?, ?, ?, ?) }");

        cs.setString(1, txtVin.getText().trim());
        cs.setInt(2, Integer.parseInt(txtIdMarca.getText().trim()));
        cs.setString(3, txtPlaca.getText().trim());
        cs.setInt(4, Integer.parseInt(txtIdEstado.getText().trim()));
        cs.setString(5, txtModelo.getText().trim());
        cs.setInt(6, Integer.parseInt(txtAño.getText().trim()));
        cs.setString(7, txtColor.getText().trim());

        cs.execute();

        JOptionPane.showMessageDialog(this, "Vehículo actualizado correctamente.");
        cs.close();
        
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al actualizar vehículo: " + ex.getMessage());
    }
    //Limpiar campos
    txtVin.setText("");
    txtIdMarca.setText("");
    txtNombreMarca.setText("");
    txtPlaca.setText("");
    txtIdEstado.setText("");
    txtNombreEstado.setText("");
    txtModelo.setText("");
    txtAño.setText("");
    txtColor.setText("");
    txtPrecioVenta.setText("");

    // Ubicar el cursor en el campo VIN
    txtVin.requestFocus();                         
    }//GEN-LAST:event_btnActualizarVehiculoActionPerformed

    private void btnConsultarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMarcaActionPerformed
        // TODO add your handling code here:
 try {
        // 1. Establecer la conexión a la base de datos
        Connection conn = SesionUsuario.conexion;

        // 2. Preparar la llamada a la función
        // El nombre de la función debe estar en mayúsculas si es cómo se creó en Oracle.
        CallableStatement cs = conn.prepareCall("{? = call PROYECTOBD.OBTENER_NOMBRE_MARCA(?)}");


        // 3. Registrar el parámetro de salida (la función devuelve un VARCHAR)
        cs.registerOutParameter(1, java.sql.Types.VARCHAR);

        // 4. Obtener el valor del campo txtIdMarca (ahora ya se pasa como un String)
        String idMarca = txtIdMarca.getText().trim(); // Ahora es un String

        // 5. Establecer el parámetro de entrada (id_marca) como String
        cs.setString(2, idMarca); // Cambié a setString porque id_marca es de tipo VARCHAR2

        // 6. Ejecutar la consulta
        cs.execute();

        // 7. Obtener el resultado y mostrarlo en txtMarca
        String nombreMarca = cs.getString(1);
        txtNombreMarca.setText(nombreMarca);

        // 8. Cerrar los recursos
        cs.close();
        

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnConsultarMarcaActionPerformed

    private void btnConsultarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstadoActionPerformed
        // TODO add your handling code here:
try {
        Connection conn = SesionUsuario.conexion;

        CallableStatement cs = conn.prepareCall("{ ? = call PROYECTOBD.OBTENER_NOMBRE_ESTADO(?) }");

        cs.registerOutParameter(1, java.sql.Types.VARCHAR);

        int idEstado = Integer.parseInt(txtIdEstado.getText().trim());
        cs.setInt(2, idEstado);

        cs.execute();

        String nombreEstado = cs.getString(1);
        txtNombreEstado.setText(nombreEstado);

        cs.close();

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnConsultarEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarVehiculo;
    private javax.swing.JButton btnConsultarEstado;
    private javax.swing.JButton btnConsultarMarca;
    private javax.swing.JButton btnConsultarVin;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtIdEstado;
    private javax.swing.JTextField txtIdMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreEstado;
    private javax.swing.JTextField txtNombreMarca;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
