/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autoventasbd2kevinramirez;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection; 
import javax.swing.JOptionPane;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;


/**
 *
 * @author kevin
 */
public class Cuotas extends javax.swing.JFrame {

    /**
     * Creates new form Cuotas
     */
    public Cuotas() {
        initComponents();
        //para permitir seleccionar el estado de la cuota ya sea "pendiente" o "pagada"  en la tabla 
        JComboBox<String> comboEstado = new JComboBox<>(new String[]{"pendiente", "pagada"});
        tablaCuotas.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(comboEstado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuotas = new javax.swing.JTable();
        btnConsultarIdVenta = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Cuotas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("ID Venta");

        txtIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVentaActionPerformed(evt);
            }
        });

        tablaCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Cuota", "Fecha Pago", "Monto", "Interes", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaCuotas);

        btnConsultarIdVenta.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarIdVenta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarIdVenta.setText("Consultar");
        btnConsultarIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarIdVentaActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnConsultarIdVenta))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarCampos)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarIdVenta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnRegresar)
                    .addComponent(btnLimpiarCampos))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCuotasDesdeProcedimiento() {
    DefaultTableModel modelo = (DefaultTableModel) tablaCuotas.getModel();
    modelo.setRowCount(0); // limpia la tabla

    try {
        Connection conn = SesionUsuario.conexion;
        int idVenta = Integer.parseInt(txtIdVenta.getText().trim());

        CallableStatement cs = conn.prepareCall("{ call proyectobd.consultar_cuotas_venta(?, ?) }");
        cs.setInt(1, idVenta);
        cs.registerOutParameter(2, oracle.jdbc.OracleTypes.CURSOR); // Necesita ojdbc

        cs.execute();

        ResultSet rs = (ResultSet) cs.getObject(2);

        boolean hayResultados = false;
        /*La llamada a rs.next() mueve el cursor del ResultSet a la siguiente fila del conjunto de resultados.
        Devuelve true si existe una fila siguiente, y false si ya no hay más.*/
        while (rs.next()) {
            hayResultados = true; // al menos una fila encontrada
            modelo.addRow(new Object[]{
                rs.getInt("id_cuota"),
                rs.getDate("fecha_pago"),
                rs.getDouble("monto"),
                rs.getDouble("interes"),
                rs.getString("estado")
            });
        }

        if (!hayResultados) {
            JOptionPane.showMessageDialog(this, "No se encontraron cuotas para el ID de venta ingresado.");
        }

        rs.close();
        cs.close();
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Ingrese un ID de venta válido (número entero).");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al consultar cuotas: " + ex.getMessage());
        ex.printStackTrace();
    }
}

private void aplicarCambios() {
        try {
            Connection conn = SesionUsuario.conexion;
            DefaultTableModel modelo = (DefaultTableModel) tablaCuotas.getModel();
            // recorre cada fila de la tabla 
            for (int i = 0; i < modelo.getRowCount(); i++) {
                int idCuota = (int) modelo.getValueAt(i, 0);
                String estado = (String) modelo.getValueAt(i, 4);
            //Llama al procedimiento para actualizar estado de la fila
                CallableStatement cs = conn.prepareCall("{ call proyectobd.actualizar_estado_cuota(?, ?) }");
                cs.setInt(1, idCuota);
                cs.setString(2, estado.toLowerCase()); // asegúrate que sea 'pagada' o 'pendiente'
                cs.execute();
                cs.close();
            }

            JOptionPane.showMessageDialog(this, "Cambios aplicados correctamente.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al aplicar cambios: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void txtIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVentaActionPerformed

    private void btnConsultarIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarIdVentaActionPerformed
        cargarCuotasDesdeProcedimiento();
    }//GEN-LAST:event_btnConsultarIdVentaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        aplicarCambios();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        Navegacion.mostrarMenuPrincipalPorRol(); // Abre el menú correspondiente segun el rol del usuario
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaCuotas.getModel();
        modelo.setRowCount(0); // limpia la tabla
        txtIdVenta.setText("");
        txtIdVenta.requestFocus();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarIdVenta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCuotas;
    private javax.swing.JTextField txtIdVenta;
    // End of variables declaration//GEN-END:variables
}
