/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autoventasbd2kevinramirez;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class EliminarCostosImportacion extends javax.swing.JFrame {

    /**
     * Creates new form EliminarCostosImportacion
     */
    public EliminarCostosImportacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtVin = new javax.swing.JTextField();
        txtIdImportacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConsultarPorVin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioQuetzales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTraidaQuetzales = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtImpuesto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTramites = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCostoPlacas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOtrosGastos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        btnEliminarCostos = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Eliminar costos de importacion ");

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("VIN");

        txtIdImportacion.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("ID importacion");

        btnConsultarPorVin.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarPorVin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarPorVin.setText("Consultar");
        btnConsultarPorVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPorVinActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Precio en Quetzales");

        txtPrecioQuetzales.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Costo traida en quetzales");

        txtTraidaQuetzales.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Impuesto");

        txtImpuesto.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Tramites");

        txtTramites.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Costo Placas");

        txtCostoPlacas.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Otros gastos");

        txtOtrosGastos.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Costo total");

        txtCostoTotal.setEditable(false);

        btnEliminarCostos.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarCostos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarCostos.setText("Eliminar");
        btnEliminarCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCostosActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsultarPorVin))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCostoPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(txtImpuesto)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrecioQuetzales, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdImportacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTraidaQuetzales, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTramites, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(txtOtrosGastos)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEliminarCostos)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarCampos)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdImportacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnConsultarPorVin))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioQuetzales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTraidaQuetzales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTramites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCostoPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtOtrosGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnEliminarCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarCampos))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        new CostosImportacion().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnConsultarPorVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPorVinActionPerformed
        try {
                // 1. Obtener el VIN del campo de texto
                String vin = txtVin.getText().trim();

                if (vin.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor ingresa un VIN.");
                    return;
                }

                // Establecer la conexión
                Connection conn = SesionUsuario.conexion;

                // Llamar al procedimiento para obtener el ID de importación
                CallableStatement cs = conn.prepareCall("{ call PROYECTOBD.obtener_id_importacion_por_vin(?, ?) }");

                // Pasar el VIN al procedimiento
                cs.setString(1, vin);

                // Registrar el parámetro de salida para el ID de importación
                cs.registerOutParameter(2, java.sql.Types.INTEGER);

                // Ejecutar el procedimiento
                cs.execute();

                // Obtener el ID de importación
                int idImportacion = cs.getInt(2);

                // Si no existe un ID de importación para el VIN, mostrar mensaje
                if (cs.wasNull()) {
                    JOptionPane.showMessageDialog(null, "No se encontró ninguna importación para este VIN.");
                    cs.close();
                    return;
                } else {
                    // Si se encuentra un ID de importación, mostrarlo en el campo de texto
                    txtIdImportacion.setText(String.valueOf(idImportacion)); 
                }

                // Ahora que tenemos el ID de importación, consultamos los costos asociados
                // Llamar al procedimiento de consulta de los costos de importación
                cs = conn.prepareCall("{ call PROYECTOBD.obtener_costos_importacion(?, ?, ?, ?, ?, ?, ?, ?) }");

                // Pasar el ID de importación al procedimiento
                cs.setInt(1, idImportacion);

                // Registrar las salidas del procedimiento
                cs.registerOutParameter(2, java.sql.Types.DECIMAL);
                cs.registerOutParameter(3, java.sql.Types.DECIMAL);
                cs.registerOutParameter(4, java.sql.Types.DECIMAL);
                cs.registerOutParameter(5, java.sql.Types.DECIMAL);
                cs.registerOutParameter(6, java.sql.Types.DECIMAL);
                cs.registerOutParameter(7, java.sql.Types.DECIMAL);
                cs.registerOutParameter(8, java.sql.Types.DECIMAL);

                // Ejecutar el procedimiento
                cs.execute();

                // Obtener los valores de los costos de importación
                double precioQuetzales = cs.getDouble(2);
                double costoTraidaQuetzales = cs.getDouble(3);
                double impuestos = cs.getDouble(4);
                double tramites = cs.getDouble(5);
                double placas = cs.getDouble(6);
                double otrosGastos = cs.getDouble(7);
                double costoTotal = cs.getDouble(8);

                // Comprobar si los valores obtenidos son nulos (no existen datos)
                if (precioQuetzales == 0 && costoTraidaQuetzales == 0 && impuestos == 0 && tramites == 0 && placas == 0 && otrosGastos == 0 && costoTotal == 0) {
                    JOptionPane.showMessageDialog(null, "No se encontraron datos de costos para este ID de importación.");
                } else {
                    // Si los datos existen, mostrar en los campos correspondientes
                    txtPrecioQuetzales.setText(String.format("%.2f", precioQuetzales));
                    txtTraidaQuetzales.setText(String.format("%.2f", costoTraidaQuetzales));
                    txtImpuesto.setText(String.format("%.2f", impuestos));
                    txtTramites.setText(String.format("%.2f", tramites));
                    txtCostoPlacas.setText(String.format("%.2f", placas));
                    txtOtrosGastos.setText(String.format("%.2f", otrosGastos));
                    txtCostoTotal.setText(String.format("%.2f", costoTotal));
                }

                // Cerrar el CallableStatement
                cs.close();

            } catch (SQLException ex) {
                // Manejo de errores de SQL
                JOptionPane.showMessageDialog(null, "Error al consultar los datos: " + ex.getMessage());
                ex.printStackTrace();
            } catch (NumberFormatException ex) {
                // Manejo de errores si el VIN no es válido
                JOptionPane.showMessageDialog(null, "Por favor ingresa un VIN válido.");
            }
    }//GEN-LAST:event_btnConsultarPorVinActionPerformed

    private void btnEliminarCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCostosActionPerformed
    try {
        // Obtener el id_importacion desde el campo de texto (txtIdImportacion)
        String idImportacionStr = txtIdImportacion.getText().trim();
        
        if (idImportacionStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un ID de importación.");
            return;
        }

        // Convertir el id_importacion a número
        int idImportacion = Integer.parseInt(idImportacionStr);

        // Preguntar si está seguro de eliminar los costos
        int confirmation = JOptionPane.showConfirmDialog(null, 
                "¿Estás seguro de que deseas eliminar los costos de importación para el ID " + idImportacion + "?",
                "Confirmación de eliminación",
                JOptionPane.YES_NO_OPTION);
        
        if (confirmation == JOptionPane.NO_OPTION) {
            return;  // Si el usuario elige "NO", no se hace nada.
        }

        // Establecer la conexión
        Connection conn = SesionUsuario.conexion;

        // Llamar al procedimiento de eliminación
        CallableStatement cs = conn.prepareCall("{ call PROYECTOBD.eliminar_costos_importacion(?) }");

        // Pasar el id_importacion al procedimiento
        cs.setInt(1, idImportacion);

        // Ejecutar el procedimiento
        cs.execute();

        // Confirmación al usuario
        JOptionPane.showMessageDialog(null, "Los costos de importación han sido eliminados.");

        // Limpiar los campos
        txtPrecioQuetzales.setText("");
        txtTraidaQuetzales.setText("");
        txtImpuesto.setText("");
        txtTramites.setText("");
        txtCostoPlacas.setText("");
        txtOtrosGastos.setText("");
        txtCostoTotal.setText("");
        txtIdImportacion.setText("");
        txtVin.setText("");
        
        txtVin.requestFocus();

    } catch (SQLException ex) {
        // Manejo de errores
        JOptionPane.showMessageDialog(null, "Error al eliminar los datos: " + ex.getMessage());
        ex.printStackTrace();
    } catch (NumberFormatException ex) {
        // Si el ID de importación no es un número válido
        JOptionPane.showMessageDialog(null, "Por favor ingresa un ID de importación válido.");
    }
    }//GEN-LAST:event_btnEliminarCostosActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        txtPrecioQuetzales.setText("");
        txtTraidaQuetzales.setText("");
        txtImpuesto.setText("");
        txtTramites.setText("");
        txtCostoPlacas.setText("");
        txtOtrosGastos.setText("");
        txtCostoTotal.setText("");
        txtIdImportacion.setText("");
        
        txtVin.requestFocus();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCostosImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCostosImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCostosImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCostosImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCostosImportacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarPorVin;
    private javax.swing.JButton btnEliminarCostos;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCostoPlacas;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtIdImportacion;
    private javax.swing.JTextField txtImpuesto;
    private javax.swing.JTextField txtOtrosGastos;
    private javax.swing.JTextField txtPrecioQuetzales;
    private javax.swing.JTextField txtTraidaQuetzales;
    private javax.swing.JTextField txtTramites;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
