/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autoventasbd2kevinramirez;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class EliminarImportacion extends javax.swing.JFrame {

    /**
     * Creates new form EliminarImportacion
     */
    public EliminarImportacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVin = new javax.swing.JTextField();
        btnConsultarPorVin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdImportacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaImportacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPaisOrigen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Eliminar Importacion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("VIN");

        btnConsultarPorVin.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarPorVin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarPorVin.setText("Consultar");
        btnConsultarPorVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPorVinActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("ID importacion");

        txtIdImportacion.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Fecha Importacion");

        txtFechaImportacion.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Pais origen");

        txtPaisOrigen.setEditable(false);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFechaImportacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarPorVin)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdImportacion, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaisOrigen))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCampos)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPorVin)
                    .addComponent(jLabel3)
                    .addComponent(txtIdImportacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaImportacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnLimpiarCampos)
                    .addComponent(btnRegresar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPorVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPorVinActionPerformed
try {
            String vin = txtVin.getText().trim();

            if (vin.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingresa un VIN.");
                return;
            }

            Connection conn = SesionUsuario.conexion;
            CallableStatement cs = conn.prepareCall("{ call PROYECTOBD.obtener_importacion_por_vin(?, ?, ?, ?) }");

            cs.setString(1, vin);
            cs.registerOutParameter(2, java.sql.Types.INTEGER); // id_importacion
            cs.registerOutParameter(3, java.sql.Types.DATE);    // fecha
            cs.registerOutParameter(4, java.sql.Types.VARCHAR); // país

            cs.execute();

            int id = cs.getInt(2);
            java.sql.Date fecha = cs.getDate(3);
            String pais = cs.getString(4);

            if (cs.wasNull() || id == 0 || fecha == null) {
                JOptionPane.showMessageDialog(null, "No se encontró importación registrada para este VIN.");
                txtIdImportacion.setText("");
                txtFechaImportacion.setText("");
                txtPaisOrigen.setText("");
            } else {
                txtIdImportacion.setText(String.valueOf(id));
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String fechaFormateada = sdf.format(fecha);
                txtFechaImportacion.setText(fechaFormateada);

                txtPaisOrigen.setText(pais);
            }

            cs.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al consultar importación: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnConsultarPorVinActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        new Importacion().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        txtVin.setText("");
        txtIdImportacion.setText("");
        txtFechaImportacion.setText("");
        txtPaisOrigen.setText("");
        
        txtVin.requestFocus();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int confirm = JOptionPane.showConfirmDialog(null, 
                "¿Estás seguro de que deseas eliminar esta importación?", 
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            Connection conn = SesionUsuario.conexion;
            CallableStatement cs = conn.prepareCall("{ call PROYECTOBD.eliminar_importacion(?) }");

            int idImportacion = Integer.parseInt(txtIdImportacion.getText().trim());
            cs.setInt(1, idImportacion);

            cs.execute();
            cs.close();

            JOptionPane.showMessageDialog(null, "Importación eliminada correctamente.");

            // Limpiar campos
            txtIdImportacion.setText("");
            txtVin.setText("");
            txtFechaImportacion.setText("");
            txtPaisOrigen.setText("");
            
            txtVin.requestFocus();

        } catch (SQLException ex) {
            if (ex.getErrorCode() == 20051) {
                JOptionPane.showMessageDialog(null, "No se encontró una importación con ese ID.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar: " + ex.getMessage());
            }
            ex.printStackTrace();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ID de importación inválido.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarImportacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarImportacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarPorVin;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFechaImportacion;
    private javax.swing.JTextField txtIdImportacion;
    private javax.swing.JTextField txtPaisOrigen;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
