/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autoventasbd2kevinramirez;

/**
 *
 * @author kevin
 */
public class Importacion extends javax.swing.JFrame {

    /**
     * Creates new form MainImportacion
     */
    public Importacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrearImportacion = new javax.swing.JButton();
        btnEliminarImportacion = new javax.swing.JButton();
        btnActualizarImportacion = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Menu de importaciones");

        btnCrearImportacion.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearImportacion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCrearImportacion.setText("Crear importacion");
        btnCrearImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearImportacionActionPerformed(evt);
            }
        });

        btnEliminarImportacion.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarImportacion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarImportacion.setText("Eliminar Importacion");
        btnEliminarImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarImportacionActionPerformed(evt);
            }
        });

        btnActualizarImportacion.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarImportacion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnActualizarImportacion.setText("Actualizar Importacion");
        btnActualizarImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarImportacionActionPerformed(evt);
            }
        });

        btnMenuPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        btnMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarImportacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarImportacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearImportacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMenuPrincipal)
                        .addGap(132, 132, 132))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnCrearImportacion)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarImportacion)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarImportacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnMenuPrincipal)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearImportacionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CrearImportacion().setVisible(true);
    }//GEN-LAST:event_btnCrearImportacionActionPerformed

    private void btnActualizarImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarImportacionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ActualizarImportacion().setVisible(true);
    }//GEN-LAST:event_btnActualizarImportacionActionPerformed

    private void btnEliminarImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImportacionActionPerformed
        this.setVisible(false);
        new EliminarImportacion().setVisible(true);
    }//GEN-LAST:event_btnEliminarImportacionActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Navegacion.mostrarMenuPrincipalPorRol(); // Abre el menú correspondiente segun el rol del usuario
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Importacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Importacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarImportacion;
    private javax.swing.JButton btnCrearImportacion;
    private javax.swing.JButton btnEliminarImportacion;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
