/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autoventasbd2kevinramirez;
import java.sql.CallableStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Types;



/**
 *
 * @author kevin
 */
public class MarcaVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form MarcaVehiculo
     */
    public MarcaVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreMarca = new javax.swing.JTextField();
        btnConsultarMarca = new javax.swing.JButton();
        btnCrearNuevoID = new javax.swing.JButton();
        btnCrearMarca = new javax.swing.JButton();
        btnActualizarMarca = new javax.swing.JButton();
        btnEliminarMarca = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Id Marca");

        txtIdMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMarcaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Nombre Marca");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Marca Vehiculos");

        btnConsultarMarca.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarMarca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnConsultarMarca.setText("Consultar");
        btnConsultarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMarcaActionPerformed(evt);
            }
        });

        btnCrearNuevoID.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearNuevoID.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCrearNuevoID.setText("Nuevo ID");
        btnCrearNuevoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevoIDActionPerformed(evt);
            }
        });

        btnCrearMarca.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearMarca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCrearMarca.setText("Crear");
        btnCrearMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMarcaActionPerformed(evt);
            }
        });

        btnActualizarMarca.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarMarca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnActualizarMarca.setText("Actualizar");
        btnActualizarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMarcaActionPerformed(evt);
            }
        });

        btnEliminarMarca.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarMarca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarMarca.setText("Eliminar");
        btnEliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMarcaActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrearNuevoID)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearMarca)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnRegresar)
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizarMarca)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarMarca))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultarMarca)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearNuevoID)
                        .addComponent(btnCrearMarca))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarMarca)
                            .addComponent(btnEliminarMarca))
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMarcaActionPerformed

    private void btnCrearNuevoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevoIDActionPerformed
        try {
               Connection conn = SesionUsuario.conexion;
               CallableStatement cstmt = conn.prepareCall("{? = call proyectobd.obtener_nuevo_id_marca()}");
               cstmt.registerOutParameter(1, Types.INTEGER);
               cstmt.execute();
               int nuevoId = cstmt.getInt(1);
               txtIdMarca.setText(String.valueOf(nuevoId));
               txtIdMarca.setEditable(false);
               txtNombreMarca.setText("");
               txtNombreMarca.requestFocus();
           } catch (SQLException e) {
               e.printStackTrace();
               JOptionPane.showMessageDialog(this, "Error al generar ID de marca.");
        }
    }//GEN-LAST:event_btnCrearNuevoIDActionPerformed

    private void btnConsultarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMarcaActionPerformed
        try {
            int idMarca = Integer.parseInt(txtIdMarca.getText().trim());

            Connection conn = SesionUsuario.conexion;
            CallableStatement cstmt = conn.prepareCall("{ ? = call proyectobd.obtener_nombre_marca(?) }");

            cstmt.registerOutParameter(1, Types.VARCHAR); // el valor que devuelve la función
            cstmt.setInt(2, idMarca);

            cstmt.execute();

            String nombre = cstmt.getString(1); // el resultado está en el primer parámetro
            txtNombreMarca.setText(nombre);
            txtNombreMarca.setEditable(true); // puedes decidir si lo dejas editable o no

            JOptionPane.showMessageDialog(this, "Consulta completada.");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al consultar la marca: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnConsultarMarcaActionPerformed

    private void btnActualizarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMarcaActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea modificar el nombre referente al ID marca?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
               int idMarca = Integer.parseInt(txtIdMarca.getText().trim());
               String nuevoNombre = txtNombreMarca.getText().trim();

               Connection conn = SesionUsuario.conexion;
               CallableStatement cstmt = conn.prepareCall("{call proyectobd.actualizar_marca(?, ?)}");
               cstmt.setInt(1, idMarca);
               cstmt.setString(2, nuevoNombre);
               cstmt.execute();

               JOptionPane.showMessageDialog(this, "Marca actualizada correctamente.");
           } catch (SQLException ex) {
               ex.printStackTrace();
               JOptionPane.showMessageDialog(this, "Error al actualizar la marca.");
           }
       }
    }//GEN-LAST:event_btnActualizarMarcaActionPerformed

    private void btnEliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMarcaActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar esta marca?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            int idMarca = Integer.parseInt(txtIdMarca.getText().trim());

            Connection conn = SesionUsuario.conexion;
            CallableStatement cstmt = conn.prepareCall("{call proyectobd.eliminar_marca(?)}");
            cstmt.setInt(1, idMarca);
            cstmt.execute();

            JOptionPane.showMessageDialog(this, "Marca eliminada correctamente.");
            txtIdMarca.setText("");
            txtNombreMarca.setText("");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al eliminar la marca.");
        }
    }
    }//GEN-LAST:event_btnEliminarMarcaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        Navegacion.mostrarMenuPrincipalPorRol(); // Abre el menú correspondiente segun el rol del usuario
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMarcaActionPerformed
       
       String nombreMarca = txtNombreMarca.getText().trim();

       if (nombreMarca.isEmpty()) {
           JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la marca.");
           return;
       }

       try {
           Connection conn = SesionUsuario.conexion;
           CallableStatement cstmt = conn.prepareCall("{call proyectobd.insertar_marca_vehiculo(?)}");

           
           cstmt.setString(1, nombreMarca);
           cstmt.execute();

           JOptionPane.showMessageDialog(this, "Marca insertada correctamente.");
           // Limpieza y recarga
       } catch (SQLException ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Error al insertar marca:\n" + ex.getMessage());
       }
       txtIdMarca.setEditable(true);
    }//GEN-LAST:event_btnCrearMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMarca;
    private javax.swing.JButton btnConsultarMarca;
    private javax.swing.JButton btnCrearMarca;
    private javax.swing.JButton btnCrearNuevoID;
    private javax.swing.JButton btnEliminarMarca;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIdMarca;
    private javax.swing.JTextField txtNombreMarca;
    // End of variables declaration//GEN-END:variables
}
